feat: implement league and table extraction for multiple countries in scraper

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -9,7 +9,7 @@ on:
     branches: [ main ]
 
 jobs:
-  scrape1:
+  extract_matches:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -36,7 +36,37 @@ jobs:
           FIREBASE_STORAGE_BUCKET: fufutebol.firebasestorage.app
 
       - name: Run main scraper for ${{ matrix.country }}
-        run: python main.py --country ${{ matrix.country }}
+        run: python matches.py --country ${{ matrix.country }}
+
+      - name: Check chromedriver version
+        run: |
+          which chromedriver || echo "chromedriver not found"
+          chromedriver --version || echo "chromedriver not available"
+  extract_tables:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Set GOOGLE_APPLICATION_CREDENTIALS
+        run: |
+          mkdir -p database
+          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" | base64 --decode > database/key.json
+        env:
+          FIREBASE_STORAGE_BUCKET: fufutebol.firebasestorage.app
+
+      - name: Run main scraper for ${{ matrix.country }}
+        run: python tables.py
 
       - name: Check chromedriver version
         run: |
